---
- name: Configure streaming telemetry destinations
  hosts: nxos_vteps
  gather_facts: no

  tasks:
    - name: Configure destinations
      nxos_config:
        src: 10.telemetry_cli.j2
      vars:
        student_id: FIXME_MY_STUDENT_ID
